env:
  browser: true
  commonjs: true
  es2021: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
rules: { "quotes": ["error", "single"] }
require-jsdoc:
  [
    "error",
    {
      "require":
        {
          "FunctionDeclaration": true,
          "MethodDefinition": false,
          "ClassDeclaration": false,
          "ArrowFunctionExpression": false,
          "FunctionExpression": false,
        },
    },
  ]
